# Generated by Django 5.2.15 on 2026-06-26 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('container_number', models.CharField(max_length=20, unique=True)),
                ('size', models.CharField(choices=[('20FT', '20 Feet Standard'), ('40FT', '40 Feet Standard'), ('40HC', '40 Feet High Cube')], max_length=5)),
                ('seal_number', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bl_number', models.CharField(max_length=50, unique=True, verbose_name='Bill of Lading Number')),
                ('transaction_type', models.CharField(choices=[('IMPORT', 'Import'), ('EXPORT', 'Export')], max_length=6)),
                ('shipper', models.CharField(max_length=100)),
                ('consignee', models.CharField(max_length=100)),
                ('origin_port', models.CharField(max_length=100)),
                ('destination_port', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Administration'), ('CUSTOMS_CLEARANCE', 'Customs Clearance'), ('RELEASED', 'Released/Completed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CostComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_type', models.CharField(choices=[('THC', 'Terminal Handling Charge'), ('DEMURRAGE', 'Demurrage Fee'), ('DETENTION', 'Detention Fee'), ('CUSTOMS_DUTY', 'Pajak / Bea Masuk'), ('EDI_FEE', 'Biaya EDI Dokumen'), ('DOCUMENTATION', 'Biaya Manifest/Dokumen')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='IDR', max_length=3)),
                ('is_paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('container', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='api_logistik.container')),
            ],
        ),
        migrations.AddField(
            model_name='container',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='containers', to='api_logistik.shipment'),
        ),
    ]
